### ISSUE TITLE
pquery - bad rule

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_lexers#12]
item
      DisplayName = 'Builtin Function'
      StyleName = 'Id'
      ConditionList = <
        item
          TagList.Strings = (
            '        | Access.Database'
            '        | ActiveDirectory.Domains'
            '        | AdoDotNet.DataSource'
            '        | AdoDotNet.Query'
            '        | AnalysisServices.Database'
            '        | AnalysisServices.Databases'
            '        | AzureStorage.Blobs'
            '        | AzureStorage.Tables'
            '        | Binary.Buffer'
            '        | Binary.Combine'

это вообще что такое? что ты хотел? зачем светить эти слова?

**Comment by ahreenah** [comment]
Вроде это что то зарезервированное

**Comment by Alexey-T** [comment]
что??
