### ISSUE TITLE
pquery- hex/octal/binary

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_lexers#23]
посмотреть есть ли в языке такие числа и как - и дать парсер для них
стиль тот же что для целых

**Comment by ahreenah** [comment]
нет, реализованы через строки в стандартной библиотеке

**Comment by Alexey-T** [comment]
https://docs.microsoft.com/en-us/powerquery-m/power-query-m-language-specification
тут не описано?

**Comment by Alexey-T** [comment]
описано там- есть  hex

**Comment by ahreenah** [comment]
fix
