### ISSUE TITLE
pquery- посветить все другие символы тоже (= , . ; / + - * < > ! |)

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_lexers#25]

**Comment by Alexey-T** [comment]
Expression = '[\=\,\.\;/\+\-\*\<\>\!\|\(\)\{\}]'

ескейпить надо минимум! многие символы не требуют это
надо: . \ - * [ ]

**Comment by ahreenah** [comment]
вроде как все скобки надо

**Comment by Alexey-T** [comment]
скобки- да
