### ISSUE TITLE
pquery - стиль зачем пестрый?

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_lexers#8]
item
      DisplayName = 'Operator'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clFuchsia
      Font.Height = -13
      Font.Name = 'Courier New'
      Font.Style = []
      FormatFlags = [ffItalic, ffUnderline, ffStrikeOut, ffReadOnly, ffHidden, ffFontName, ffFontSize, ffFontCharset, ffVertAlign]
    end

**Comment by Alexey-T** [comment]
not fixed

**Comment by medvosa** [comment]
/Users/alme/Desktop/Screen Shot 2020-02-06 at 15.07.51.png

**Comment by medvosa** [comment]
Screen Shot 2020-02-06 at 15.07.51

**Comment by ahreenah** [comment]
я поменял

**Comment by Alexey-T** [comment]
item
      DisplayName = 'Operator'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 5796629
      Font.Height = -13
      Font.Name = 'Courier New'
      Font.Style = []
      FormatFlags = [ffItalic, ffUnderline, ffStrikeOut, ffReadOnly, ffHidden, ffFontName, ffFontSize, ffFontCharset, ffVertAlign]
    end

not fixed
